### ISSUE TITLE
請問有沒有方法可以忽略 @media 區塊內不轉換

### ISSUE THREAD

**Issue by imagine10255** [hnzycfcfed/styled-px2vw#3]
請問有沒有方法可以忽略 @media 區塊內不轉換 ?

我這邊想到一個方案是,
lg 以下尺寸, 寫px 自動轉換為vw
lg 尺寸不進行轉換, 手動寫 px

**Comment by domisolo** [comment]
您好，在编写代码的时候将px写成PX，将不会被转换
